name: grocery_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  async: ^2.11.0
  bloc: ^7.0.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^7.0.0
  freezed_annotation: ^2.4.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^2.4.1
  import_sorter: ^4.6.0
  intl_translation: ^0.20.0
  injectable_generator:
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
